// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TakeHomeExercise4System.Entities;

[Index("CarClassId", Name = "IDX_Cars_CarClassID")]
[Index("MemberId", Name = "IDX_Cars_MemberID")]
[Index("SerialNumber", Name = "UQ__Cars__048A000814F21EE9", IsUnique = true)]
public partial class Car
{
    [Key]
    [Column("CarID")]
    public int CarId { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string SerialNumber { get; set; }

    [Required]
    [StringLength(6)]
    [Unicode(false)]
    public string Ownership { get; set; }

    [Column("CarClassID")]
    public int CarClassId { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string State { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("CarClassId")]
    [InverseProperty("Cars")]
    public virtual CarClass CarClass { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("Cars")]
    public virtual Member Member { get; set; }

    [InverseProperty("Car")]
    public virtual ICollection<RaceDetail> RaceDetails { get; set; } = new List<RaceDetail>();
}