// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TakeHomeExercise4System.Entities;

[Index("EmployeeId", Name = "IDX_Invoices_EmployeeID")]
public partial class Invoice
{
    [Key]
    [Column("InvoiceID")]
    public int InvoiceId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InvoiceDate { get; set; }

    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Column(TypeName = "money")]
    public decimal SubTotal { get; set; }

    [Column("GST", TypeName = "money")]
    public decimal Gst { get; set; }

    [Column(TypeName = "money")]
    public decimal? Total { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("Invoices")]
    public virtual Employee Employee { get; set; }

    [InverseProperty("Invoice")]
    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    [InverseProperty("Invoice")]
    public virtual ICollection<RaceDetail> RaceDetails { get; set; } = new List<RaceDetail>();

    [InverseProperty("Invoice")]
    public virtual ICollection<StoreRefund> StoreRefundInvoices { get; set; } = new List<StoreRefund>();

    [InverseProperty("OriginalInvoice")]
    public virtual ICollection<StoreRefund> StoreRefundOriginalInvoices { get; set; } = new List<StoreRefund>();
}