// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TakeHomeExercise4System.Entities;

[Index("InvoiceId", Name = "IDX_InvoiceDetails_InvoiceID")]
[Index("ProductId", Name = "IDX_InvoiceDetails_ProductID")]
public partial class InvoiceDetail
{
    [Key]
    [Column("InvoiceDetailID")]
    public int InvoiceDetailId { get; set; }

    [Column("InvoiceID")]
    public int InvoiceId { get; set; }

    [Column("ProductID")]
    public int ProductId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal? Price { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("InvoiceId")]
    [InverseProperty("InvoiceDetails")]
    public virtual Invoice Invoice { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("InvoiceDetails")]
    public virtual Product Product { get; set; }
}