// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TakeHomeExercise4System.Entities;

[Index("EmployeeId", Name = "IDX_Orders_EmployeeID")]
[Index("VendorId", Name = "IDX_Orders_VendorID")]
public partial class Order
{
    [Key]
    [Column("OrderID")]
    public int OrderId { get; set; }

    public int? OrderNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OrderDate { get; set; }

    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Column("TaxGST", TypeName = "smallmoney")]
    public decimal TaxGst { get; set; }

    [Column(TypeName = "money")]
    public decimal SubTotal { get; set; }

    [Column("VendorID")]
    public int VendorId { get; set; }

    public bool Closed { get; set; }

    [StringLength(255)]
    public string Comment { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("Orders")]
    public virtual Employee Employee { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [InverseProperty("Order")]
    public virtual ICollection<ReceiveOrder> ReceiveOrders { get; set; } = new List<ReceiveOrder>();

    [ForeignKey("VendorId")]
    [InverseProperty("Orders")]
    public virtual Vendor Vendor { get; set; }
}