// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TakeHomeExercise4System.Entities;

[Index("ProductId", Name = "IDX_OrderDetail_ProductID")]
[Index("OrderId", Name = "IDX_OrderDetails_OrderID")]
public partial class OrderDetail
{
    [Key]
    [Column("OrderDetailID")]
    public int OrderDetailId { get; set; }

    [Column("OrderID")]
    public int OrderId { get; set; }

    [Column("ProductID")]
    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public int OrderUnitSize { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal Cost { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderDetails")]
    public virtual Product Product { get; set; }

    [InverseProperty("OrderDetail")]
    public virtual ICollection<ReceiveOrderItem> ReceiveOrderItems { get; set; } = new List<ReceiveOrderItem>();

    [InverseProperty("OrderDetail")]
    public virtual ICollection<ReturnOrderItem> ReturnOrderItems { get; set; } = new List<ReturnOrderItem>();
}