// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TakeHomeExercise4System.Entities;

[Index("CategoryId", Name = "IDX_Products_CategoryID")]
public partial class Product
{
    [Key]
    [Column("ProductID")]
    public int ProductId { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string ItemName { get; set; }

    [Column(TypeName = "money")]
    public decimal ItemPrice { get; set; }

    public int QuantityOnOrder { get; set; }

    public int QuantityOnHand { get; set; }

    public int ReOrderLevel { get; set; }

    [Column(TypeName = "money")]
    public decimal ReStockCharge { get; set; }

    [Column("CategoryID")]
    public int CategoryId { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    [InverseProperty("Product")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [InverseProperty("Product")]
    public virtual ICollection<SalesCartItem> SalesCartItems { get; set; } = new List<SalesCartItem>();

    [InverseProperty("Product")]
    public virtual ICollection<StoreRefund> StoreRefunds { get; set; } = new List<StoreRefund>();

    [InverseProperty("Product")]
    public virtual ICollection<VendorCatalog> VendorCatalogs { get; set; } = new List<VendorCatalog>();
}