// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TakeHomeExercise4System.Entities;

[Index("CarId", Name = "IDX_RaceDetails_CarID")]
[Index("InvoiceId", Name = "IDX_RaceDetails_InvoiceID")]
[Index("MemberId", Name = "IDX_RaceDetails_MemberID")]
[Index("PenaltyId", Name = "IDX_RaceDetails_PenaltyID")]
[Index("RaceId", Name = "IDX_RaceDetails_RaceID")]
public partial class RaceDetail
{
    [Key]
    [Column("RaceDetailID")]
    public int RaceDetailId { get; set; }

    [Column("RaceID")]
    public int RaceId { get; set; }

    [Column("CarID")]
    public int? CarId { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    public int? Place { get; set; }

    public TimeOnly? RunTime { get; set; }

    [Column("PenaltyID")]
    public int? PenaltyId { get; set; }

    [StringLength(1048)]
    public string Comment { get; set; }

    [Column("InvoiceID")]
    public int? InvoiceId { get; set; }

    [Column(TypeName = "money")]
    public decimal RaceFee { get; set; }

    [Column(TypeName = "money")]
    public decimal RentalFee { get; set; }

    public bool Refund { get; set; }

    [StringLength(150)]
    public string RefundReason { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("CarId")]
    [InverseProperty("RaceDetails")]
    public virtual Car Car { get; set; }

    [ForeignKey("InvoiceId")]
    [InverseProperty("RaceDetails")]
    public virtual Invoice Invoice { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("RaceDetails")]
    public virtual Member Member { get; set; }

    [ForeignKey("PenaltyId")]
    [InverseProperty("RaceDetails")]
    public virtual RacePenalty Penalty { get; set; }

    [ForeignKey("RaceId")]
    [InverseProperty("RaceDetails")]
    public virtual Race Race { get; set; }
}