// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TakeHomeExercise4System.Entities;

[Index("EmployeeId", Name = "IDX_ReceiveOrders_EmployeeID")]
[Index("OrderId", Name = "IDX_ReceiveOrders_OrderID")]
public partial class ReceiveOrder
{
    [Key]
    [Column("ReceiveOrderID")]
    public int ReceiveOrderId { get; set; }

    [Column("OrderID")]
    public int OrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReceiveDate { get; set; }

    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("ReceiveOrders")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("ReceiveOrders")]
    public virtual Order Order { get; set; }

    [InverseProperty("ReceiveOrder")]
    public virtual ICollection<ReceiveOrderItem> ReceiveOrderItems { get; set; } = new List<ReceiveOrderItem>();

    [InverseProperty("ReceiveOrder")]
    public virtual ICollection<ReturnOrderItem> ReturnOrderItems { get; set; } = new List<ReturnOrderItem>();
}